# Generated by Django 4.2.1 on 2023-05-25 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QRCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=300)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("url", "url"),
                            ("me-card", "me-card"),
                            ("wifi", "wifi"),
                        ],
                        default="url",
                        max_length=300,
                    ),
                ),
                ("qr_code", models.FileField(max_length=650, upload_to="qr-codes/")),
                (
                    "source",
                    models.CharField(
                        choices=[("api-call", "api-call"), ("product", "product")],
                        default="api-call",
                        max_length=255,
                    ),
                ),
                ("url", models.CharField(blank=True, max_length=350, null=True)),
                ("name", models.CharField(blank=True, max_length=350, null=True)),
                ("email", models.CharField(blank=True, max_length=350, null=True)),
                ("phone", models.CharField(blank=True, max_length=350, null=True)),
                ("ssid", models.CharField(blank=True, max_length=350, null=True)),
                ("password", models.CharField(blank=True, max_length=350, null=True)),
                ("security", models.CharField(blank=True, max_length=350, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
