# Generated by Django 4.2.1 on 2023-05-26 04:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qr_code_api", "0004_alter_qrcode_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qrcode",
            name="qr_code",
            field=models.ImageField(blank=True, null=True, upload_to="qr-codes/"),
        ),
    ]
