# Generated by Django 4.2.1 on 2023-05-26 19:07

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("qr_code_api", "0006_alter_qrcode_options"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="qrcode",
            managers=[
                ("everything", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="qrcode",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
