# Generated by Django 4.2.1 on 2023-06-10 04:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan_name",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("pro", "Pro"),
                            ("business", "Business"),
                        ],
                        default="free",
                        max_length=300,
                    ),
                ),
                ("pricing", models.IntegerField()),
                ("description", models.TextField()),
            ],
            options={
                "verbose_name_plural": "Pricing and Plans",
            },
        ),
    ]
