# Generated by Django 4.2.1 on 2023-06-10 04:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pricing", "0002_alter_pricing_description_alter_pricing_plan_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricing",
            name="api_mo",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pricing",
            name="qr_mo",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pricing",
            name="url_mo",
            field=models.IntegerField(default=0),
        ),
    ]
