# Generated by Django 4.2.1 on 2023-06-10 04:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pricing", "0003_pricing_api_mo_pricing_qr_mo_pricing_url_mo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pricing",
            name="api_mo",
        ),
        migrations.RemoveField(
            model_name="pricing",
            name="pricing",
        ),
        migrations.RemoveField(
            model_name="pricing",
            name="qr_mo",
        ),
        migrations.RemoveField(
            model_name="pricing",
            name="url_mo",
        ),
        migrations.AddField(
            model_name="pricing",
            name="api_day",
            field=models.IntegerField(default=0, verbose_name="API Request per Day"),
        ),
        migrations.AddField(
            model_name="pricing",
            name="pricing_month",
            field=models.IntegerField(default=0, verbose_name="Pricing per Month"),
        ),
        migrations.AddField(
            model_name="pricing",
            name="qr_day",
            field=models.IntegerField(default=0, verbose_name="QR per Day"),
        ),
        migrations.AddField(
            model_name="pricing",
            name="url_day",
            field=models.IntegerField(default=0, verbose_name="URL per Day"),
        ),
    ]
