# Generated by Django 4.2.1 on 2023-05-26 05:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_alter_userprofile_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="otp",
            old_name="if_used",
            new_name="is_used",
        ),
    ]
