# Generated by Django 4.2.1 on 2023-05-26 06:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_rename_if_used_otp_is_used"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="otp",
            options={"verbose_name_plural": "OTPs"},
        ),
    ]
