# Generated by Django 4.2.1 on 2023-05-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_alter_otp_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("none", "Rather Not Say"),
                ],
                default="male",
                max_length=50,
            ),
        ),
    ]
