# Generated by Django 4.2.1 on 2023-05-28 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_usertoken"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usertoken",
            options={"verbose_name_plural": "User Token"},
        ),
        migrations.AlterField(
            model_name="usertoken",
            name="role",
            field=models.CharField(
                choices=[("api-use", "API Use"), ("app-use", "App Use")],
                default="api-use",
                max_length=255,
            ),
        ),
    ]
