# Generated by Django 4.2.1 on 2023-05-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_alter_usertoken_options_alter_usertoken_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usertoken",
            name="token",
            field=models.CharField(editable=False, max_length=255, unique=True),
        ),
    ]
