# Generated by Django 4.2.1 on 2023-06-10 04:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0012_remove_userprofile_coins_userprofile_api_mo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="api_mo",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="qr_mo",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="url_mo",
        ),
    ]
