# Generated by Django 4.2.1 on 2023-06-10 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pricing", "0004_remove_pricing_api_mo_remove_pricing_pricing_and_more"),
        (
            "accounts",
            "0013_remove_userprofile_api_mo_remove_userprofile_qr_mo_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="plan",
            field=models.ForeignKey(
                default=1,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pricing.pricing",
            ),
        ),
    ]
