# Generated by Django 4.2.1 on 2023-06-10 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0015_paymentshistory"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paymentshistory",
            options={"verbose_name_plural": "Payment History"},
        ),
        migrations.RemoveField(
            model_name="paymentshistory",
            name="instamojo_id",
        ),
        migrations.AddField(
            model_name="paymentshistory",
            name="currency",
            field=models.CharField(default="INR", max_length=255),
        ),
        migrations.AddField(
            model_name="paymentshistory",
            name="instamojo_order_id",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="paymentshistory",
            name="instamojo_payment_id",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="paymentshistory",
            name="payment_mode",
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name="paymentshistory",
            name="payment_status",
            field=models.CharField(default="not done", max_length=255),
        ),
    ]
