# Generated by Django 4.2.1 on 2023-06-10 09:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0018_alter_paymentshistory_payment_mode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymentshistory",
            name="id",
        ),
        migrations.AddField(
            model_name="paymentshistory",
            name="payment_request_id",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="paymentshistory",
            name="payment_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
