# Generated by Django 4.2.1 on 2023-06-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0019_remove_paymentshistory_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentshistory",
            name="billed_for",
            field=models.CharField(
                choices=[("1", "1"), ("3", "3"), ("6", "6"), ("12", "12")],
                default="1",
                max_length=255,
                verbose_name="Billed for mo",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="plan_expires",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
