# Generated by Django 4.2.1 on 2023-06-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0020_paymentshistory_billed_for_userprofile_plan_expires"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentshistory",
            name="billed_for",
            field=models.CharField(
                choices=[
                    ("1", "1 Month"),
                    ("3", "3 Month"),
                    ("6", "6 Month"),
                    ("12", "12 Month"),
                ],
                default="1",
                max_length=255,
                verbose_name="Billed for/mo",
            ),
        ),
    ]
