# Generated by Django 4.2.1 on 2023-05-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("url_short_api", "0003_alter_shorturl_short_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="shorturl",
            name="title",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
