# Generated by Django 4.2.1 on 2023-05-25 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("url_short_api", "0004_shorturl_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="shorturl",
            name="source",
            field=models.CharField(
                choices=[("api-call", "api-call"), ("product", "product")],
                default="product",
                max_length=255,
            ),
        ),
    ]
