# Generated by Django 4.2.1 on 2023-05-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("url_short_api", "0005_shorturl_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shorturl",
            name="source",
            field=models.CharField(
                choices=[("api-call", "api-call"), ("product", "product")],
                default="api-call",
                max_length=255,
            ),
        ),
    ]
