# Generated by Django 4.2.1 on 2023-05-25 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("url_short_api", "0006_alter_shorturl_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shorturl",
            name="source",
            field=models.CharField(
                choices=[
                    ("api-service", "API Service"),
                    ("sbcare-product", "SB Care Product"),
                ],
                default="api-service",
                max_length=255,
            ),
        ),
    ]
