# Generated by Django 4.2.1 on 2023-05-26 19:06

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("url_short_api", "0008_alter_shorturl_options"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="shorturl",
            managers=[
                ("everything", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="shorturl",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
