# Generated by Django 4.2.1 on 2023-05-24 04:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="urlshorterproduct",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="urlshorterproduct",
            name="title",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
