# Generated by Django 4.2.1 on 2023-05-24 15:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_urlshorterproduct_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="urlshorterproduct",
            name="description",
        ),
    ]
