# Generated by Django 4.2.1 on 2023-05-25 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("url_short_api", "0006_alter_shorturl_source"),
        ("products", "0003_remove_urlshorterproduct_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="urlshorterproduct",
            name="url_api",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="url_short_api.shorturl",
            ),
        ),
    ]
